version: "3.7"

services:
  workshop-api:
    container_name: workshop-api
    build:
      context: .
      target: dev
    volumes:
      - ./:/app
    ports:
      - "9000:9000"
    networks:
      - sh-go-workshop-network

  workshop-db:
    container_name: workshop-db
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "6500:5432"
    networks:
      - sh-go-workshop-network

volumes:
  postgres-db:

networks:
  sh-go-workshop-network:
    name: sh-go-workshop-network
